// Mocks generated by Mockito 5.0.17 from annotations
// in crud_hive/test/features/crud/domain/entities/task_test.dart.
// Do not manually edit this file.

import 'package:crud_hive/features/crud/domain/entities/task.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTask_0 extends _i1.Fake implements _i2.Task {}

/// A class which mocks [Task].
///
/// See the documentation for Mockito's code generation for more information.
class MockTask extends _i1.Mock implements _i2.Task {
  MockTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set name(String? _name) => super.noSuchMethod(Invocation.setter(#name, _name),
      returnValueForMissingStub: null);
  @override
  bool get isCompleted =>
      (super.noSuchMethod(Invocation.getter(#isCompleted), returnValue: false)
          as bool);
  @override
  set isCompleted(bool? _isCompleted) =>
      super.noSuchMethod(Invocation.setter(#isCompleted, _isCompleted),
          returnValueForMissingStub: null);
  @override
  set date(String? _date) => super.noSuchMethod(Invocation.setter(#date, _date),
      returnValueForMissingStub: null);
  @override
  set time(String? _time) => super.noSuchMethod(Invocation.setter(#time, _time),
      returnValueForMissingStub: null);
  @override
  _i2.Task copyWith(
          {String? name, bool? isCompleted, String? date, String? time}) =>
      (super.noSuchMethod(
          Invocation.method(#copyWith, [], {
            #name: name,
            #isCompleted: isCompleted,
            #date: date,
            #time: time
          }),
          returnValue: _FakeTask_0()) as _i2.Task);
}
